# Welcome to Jekyll!

# Site settings
title: The Dynamic Radio Sky Conference 2025
email: dynamicradiosky2025@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This conference is dedicated to the broad area of radio time domain astronomy, and reflects 
  the advances in the field over the past several years, as we work towards the transformational 
  capabilities of the SKA.

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
